name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Compile Go application (arm)
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -o app-arm .

      - name: Compile Go application (x64)
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o app-x64 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image (arm)
        run: docker push dbohry/dns-updater:arm-latest

      - name: Push Docker image (x64)
        run: docker push dbohry/dns-updater:x64-latest